### ISSUE TITLE
Bad type definitions

### ISSUE THREAD

**Issue by JimiPedros** [reactchartjs/react-chartjs-2#687]
```
Property 'type' is missing in type '{ data: { labels: string[]; datasets: { label: string; data: number[]; fill: boolean; backgroundColor: string; borderColor: string; }[]; }; options: { scales: { yAxes: { ticks: { beginAtZero: boolean; }; }[]; }; }; }' but required in type 'Props'.
```

Following example and using a Line component in typescript codebase as such results in error above
```
<Line data={data} options={options} />
```

**Comment by eligundry** [comment]
I'm running into this too. I am on react-chartjs-2 v3.0.3 and chart.js v3.3.2. Looking at the Typescript definitions in this package at it's mainly powered by the following type import:

```ts
import Chart from 'chart.js/auto'
```

But looking at the types for v3 of chart.js, `chart.js/auto` does not seem to exist. Furthermore, they really refactored how they do types in v3.

**Comment by esemeniuc** [comment]
The type property gets overridden with `type='line`', so you can put anything for the value.

See: https://github.com/reactchartjs/react-chartjs-2/blob/67cd5622d702230f1aa5e06d994134fdd451bd7b/src/index.tsx#L12

**Comment by eligundry** [comment]
Completely understand that `type` gets discarded, but I'm also seeing issues across other props related to chart.js v3 getting rid of `'chart.js/auto'`. For example the tick callbacks are impossible to type because it isn't importing the right type from chart.js.

**Comment by eligundry** [comment]
Nevermind, I think this was fixed and this issue might be closeable.

https://github.com/reactchartjs/react-chartjs-2/commit/67cd5622d702230f1aa5e06d994134fdd451bd7b

**Comment by AshotN** [comment]
When is that next release happening?

**Comment by finnmerlett** [comment]
This is still not working for me. The fix is actually changing 
```typescript
import Chart from 'chart.js/auto';
```
to this
```typescript
import * as Chart from 'chart.js/auto';
```
This is needed because the types referenced in this package as Chart.XXX are actually exported as interfaces directly from the `chart.js/auto` file, rather than as part of the Chart namespace.

**Comment by finnmerlett** [comment]
@YakovlevCoded FYI this is still not working for me. The fix is actually changing 
```typescript
import Chart from 'chart.js/auto';
```
to this
```typescript
import * as Chart from 'chart.js/auto';
```
This is needed because the types referenced in this package as Chart.XXX are actually exported as interfaces directly from the `chart.js/auto` file, rather than as part of the Chart namespace.
